export const dummyData = {
  mens: {
    title: "Mens",
    items: [
      {
        name: "Camo Down Vest",
        price: 325,
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        id: 30,
      },
      {
        name: "Floral T-shirt",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 20,
        id: 31,
      },
      {
        id: 32,
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 25,
        name: "Black & White Longsleeve",
      },
      {
        price: 25,
        name: "Pink T-shirt",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        id: 33,
      },
      {
        price: 40,
        id: 34,
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        name: "Jean Long Sleeve",
      },
      {
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        id: 35,
        price: 25,
        name: "Burgundy T-shirt",
      },
    ],
    routeName: "mens",
    id: "7guDZvA1mCee9Em0PZGO",
  },
  jackets: {
    title: "Jackets",
    items: [
      {
        price: 125,
        id: 18,
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        name: "Black Jean Shearling",
      },
      {
        price: 90,
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        id: 19,
        name: "Blue Jean Jacket",
      },
      {
        name: "Grey Jean Jacket",
        price: 90,
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        id: 20,
      },
      {
        name: "Brown Shearling",
        price: 165,
        id: 21,
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
      },
      {
        name: "Tan Trench",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 185,
        id: 22,
      },
    ],
    routeName: "jackets",
    id: "AKCNHuk4t0Xx4yPyGeHY",
  },
  womens: {
    title: "Womens",
    items: [
      {
        id: 23,
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        price: 25,
        name: "Blue Tanktop",
      },
      {
        id: 24,
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        name: "Floral Blouse",
        price: 20,
      },
      {
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        name: "Floral Dress",
        price: 80,
        id: 25,
      },
      {
        price: 80,
        name: "Red Dots Dress",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        id: 26,
      },
      {
        id: 27,
        price: 45,
        name: "Striped Sweater",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
      },
      {
        price: 135,
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        id: 28,
        name: "Yellow Track Suit",
      },
      {
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        id: 29,
        price: 20,
        name: "White Blouse",
      },
    ],
    routeName: "womens",
    id: "AwJtHPjofUJGVY2J1pGX",
  },
  sneakers: {
    title: "Sneakers",
    items: [
      {
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        id: 10,
        price: 220,
        name: "Adidas NMD",
      },
      {
        name: "Adidas Yeezy",
        id: 11,
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
      },
      {
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        name: "Black Converse",
        price: 110,
        id: 12,
      },
      {
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 160,
        id: 13,
        name: "Nike White AirForce",
      },
      {
        price: 160,
        name: "Nike Red High Tops",
        id: 14,
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
      },
      {
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        name: "Nike Brown High Tops",
        id: 15,
        price: 160,
      },
      {
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
        name: "Air Jordan Limited",
        id: 16,
      },
      {
        price: 200,
        id: 17,
        name: "Timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
      },
    ],
    routeName: "sneakers",
    id: "WR2QG0liTYDQb4Zr5uMf",
  },
  hats: {
    title: "Hats",
    items: [
      {
        name: "Brown Brim",
        id: 1,
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        price: 25,
      },
      {
        id: 2,
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 18,
        name: "Blue Beanie",
      },
      {
        id: 3,
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        price: 35,
        name: "Brown Cowboy",
      },
      {
        name: "Grey Brim",
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        id: 4,
        price: 25,
      },
      {
        id: 5,
        price: 18,
        name: "Green Beanie",
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
      },
      {
        id: 6,
        price: 14,
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        name: "Palm Tree Cap",
      },
      {
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        name: "Red Beanie",
        id: 7,
        price: 18,
      },
      {
        id: 8,
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 14,
        name: "Wolf Cap",
      },
      {
        id: 9,
        name: "Blue Snapback",
        price: 16,
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
      },
    ],
    routeName: "hats",
    id: "olLJ3Lm5cYuAjb5uMaYl",
  },
}
